trigger:
  batch: true
  branches:
    include:
    - main

pr: none

jobs:
- job: DockerDevPushAndScan

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    CONTAINER_REGISTRY: choreoctrlplane.azurecr.io
    CAPACITY_PLANNER_INIT_REPOSITORY: choreoipaas/capacity-planner-init
    CAPACITY_PLANNER_REPOSITORY: choreoipaas/capacity-planner

  steps:
  - script: |
      APP_REVISION="master-$(Build.SourceVersion)"
      echo "##vso[task.setvariable variable=APP_REVISION]${APP_REVISION}"
      echo "Generated Docker tag: ${APP_REVISION}"
    displayName: 'Generate Docker tag'
  - task: Docker@2
    displayName: 'Build and push Init Docker image'
    inputs:
      command: buildAndPush
      containerRegistry: 'wso2choreo-control-plane-acr'
      repository: $(CAPACITY_PLANNER_INIT_REPOSITORY)
      Dockerfile: 'docker-images/initContainer/Dockerfile'
      buildContext: '.'
      tags: |
        latest
        $(APP_REVISION)
  - script: |
      curl -v --header "Content-Type: application/json" \
      --request POST \
      --data '{ "newDockerImage" : "$(CONTAINER_REGISTRY)/$(CAPACITY_PLANNER_INIT_REPOSITORY):$(APP_REVISION)"}' \
      https://dev.azure.com/wso2-choreo/_apis/public/distributedtask/webhooks/dev-image-update-trigger?api-version=6.0-preview
    displayName: 'Trigger dev init image tag updating build'

  - task: Docker@2
    displayName: 'Build and push Service Docker image'
    inputs:
      command: buildAndPush
      containerRegistry: 'wso2choreo-control-plane-acr'
      repository: $(CAPACITY_PLANNER_REPOSITORY)
      Dockerfile: 'docker-images/service/Dockerfile'
      buildContext: '.'
      tags: |
        latest
        $(APP_REVISION)
  - script: |
      curl -v --header "Content-Type: application/json" \
      --request POST \
      --data '{ "newDockerImage" : "$(CONTAINER_REGISTRY)/$(CAPACITY_PLANNER_REPOSITORY):$(APP_REVISION)"}' \
      https://dev.azure.com/wso2-choreo/_apis/public/distributedtask/webhooks/dev-image-update-trigger?api-version=6.0-preview
    displayName: 'Trigger dev service image tag updating build'
  - template: templates/trivy-docker-scan.yml
    parameters:
      repository: $(CAPACITY_PLANNER_INIT_REPOSITORY)

  - template: templates/trivy-docker-scan.yml
    parameters:
      repository: $(CAPACITY_PLANNER_REPOSITORY)
