trigger: none

pr:
  branches:
    include:
      - main

variables:
- group: 'choreo-ai-capacity-planner'

pool:
  vmImage: 'ubuntu-20.04'

steps:
- script: |
    sudo wget https://dvc.org/deb/dvc.list -O /etc/apt/sources.list.d/dvc.list
    sudo apt update
    sudo apt install -y dvc python3-setuptools
    sudo dvc remote add -d --local storageremote azure://modelcontainer
    sudo dvc remote modify --local storageremote connection_string "$MODEL_CONNECTION_STRING"
    sudo dvc pull
    sudo dvc remote remove --local storageremote
    sudo apt install python3-pip
    sudo -H pip3 install --no-cache-dir -r docker-images/service/requirements.txt
    sudo pip3 install coverage
    coverage run -m unittest discover
    coverage report -m
    coverage xml
    coverage html
  displayName: 'Capacity Planner Coverage Test'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Cobertura Coverage Report'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/capacity_planner_coverage_xml.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/html'
